[WIP] support route cors config
higress-group/higress-console pull request #100
Opened 2023-02-20 02:47 UTC by jameszhangyukun

### Ⅰ. Describe what this PR did
supoort route cors config

### Ⅱ. Does this pull request fix one issue?

#61 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-02-20 02:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/higress-group/higress-console?pullRequest=100) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/higress-group/higress-console?pullRequest=100) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/higress-group/higress-console?pullRequest=100) it.</sub>

2023-02-21 03:43 UTC, jameszhangyukun commented
cc @CH3CHO

2023-02-21 04:55 UTC, CH3CHO requested changes

2023-02-21 04:55 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java
> +        public static final String CORS_MAX_AGE= "higress.io/cors-max-age";
命名格式是否需要和上面的保持一致呢？

2023-02-21 04:55 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +import com.alibaba.higress.console.controller.dto.route.*;
这里需要格式化一下，重新给import排序。

2023-02-21 04:55 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +        Integer maxAge = Integer.valueOf(metadata.getAnnotations().get(KubernetesConstants.Annotation.CORS_MAX_AGE));
是否需要考虑这些值格式不对而导致类型转换出现异常的场景？

2023-02-21 04:55 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +        List<String> exposeHeaders = Collections.singletonList(metadata.getAnnotations().get(KubernetesConstants.Annotation.CORS_EXPOSE_HEADERS));
以上几个都是列表，不是单个元素吧？

2023-02-21 04:55 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +
多余空行。

2023-02-21 04:55 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +        if (Objects.isNull(cors)) return;
单行if是否需要大括号呢？此处的做法与上面L155的做法不一致。

2023-02-21 04:55 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +        if (!CollectionUtils.isEmpty(cors.getAllowOrigins())) {
我记得CollectionUtils是有isNotEmpty方法的。

2023-02-21 04:55 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +            corsExposeHeaders = cors.getExposeHeaders().toString();
List直接toString合适吗？

2023-02-21 04:55 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +        String allowCredentials = "false";
这里的默认行为建议不做设置，以免Higress默认行为出现调整时产生冲突。

2023-02-21 06:25 UTC, jameszhangyukun commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +        Integer maxAge = Integer.valueOf(metadata.getAnnotations().get(KubernetesConstants.Annotation.CORS_MAX_AGE));
在issue https://github.com/higress-group/higress-console/issues/95 中会对进入的后端参数进行格式校验 所以我觉得在这里不校验应该也是可以的

2023-02-21 10:50 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +        Integer maxAge = Integer.valueOf(metadata.getAnnotations().get(KubernetesConstants.Annotation.CORS_MAX_AGE));
但那个机制校验的是API的输入，你这里读的是K8s的CR数据。还是要防一道的。

2023-02-21 10:55 UTC, jameszhangyukun commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +        Integer maxAge = Integer.valueOf(metadata.getAnnotations().get(KubernetesConstants.Annotation.CORS_MAX_AGE));
> 但那个机制校验的是API的输入，你这里读的是K8s的CR数据。还是要防一道的。
是的，但是如果转换的时候，出现异常，我们是直接赋值默认值，还是直接设置空对象，还是忽略
```
try{
 Boolean enabled = Boolean.valueOf(metadata.getAnnotations().get(KubernetesConstants.Annotation.ENABLE_CORS_KEY));
        Boolean allowCredentials = Boolean.valueOf(metadata.getAnnotations().get(KubernetesConstants.Annotation.CORS_ALLOW_CREDENTIALS_KEY));
        Integer maxAge = Integer.valueOf(metadata.getAnnotations().get(KubernetesConstants.Annotation.CORS_MAX_AGE_KEY));
        List<String> allowOrigins = Arrays.asList(metadata.getAnnotations().get(KubernetesConstants.Annotation.CORS_ALLOW_ORIGIN_KEY).split(CommonKey.COMMA));
        List<String> allowMethods = Arrays.asList(metadata.getAnnotations().get(KubernetesConstants.Annotation.CORS_ALLOW_METHODS_KEY).split(CommonKey.COMMA));
        List<String> allowHeaders = Arrays.asList(metadata.getAnnotations().get(KubernetesConstants.Annotation.CORS_ALLOW_HEADERS_KEY).split(CommonKey.COMMA));
        List<String> exposeHeaders = Arrays.asList(metadata.getAnnotations().get(KubernetesConstants.Annotation.CORS_EXPOSE_HEADERS_KEY).split(CommonKey.COMMA));

        CorsConfig config = CorsConfig.builder()
                .allowOrigins(allowOrigins)
                .maxAge(maxAge)
                .allowHeaders(allowHeaders)
                .allowCredentials(allowCredentials)
                .exposeHeaders(exposeHeaders)
                .allowMethods(allowMethods)
                .enabled(enabled)
                .build();
        route.setCors(config);
}
cache(Exception e){

}
```

2023-02-21 11:00 UTC, CH3CHO requested changes

2023-02-21 11:00 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +        List<String> exposeHeaders = Arrays.asList(metadata.getAnnotations().get(KubernetesConstants.Annotation.CORS_EXPOSE_HEADERS_KEY).split(CommonKey.COMMA));
下面按需写入Annotation后，这里是可能get出null的。

2023-02-21 11:02 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +        Integer maxAge = Integer.valueOf(metadata.getAnnotations().get(KubernetesConstants.Annotation.CORS_MAX_AGE));
忽略有问题的配置项吧

2023-02-22 06:52 UTC, CH3CHO approved these changes
LGTM. Thanks.

2023-02-22 06:57 UTC, merged