feature: Add eslint ts stylelint code check
higress-group/higress-console pull request #115
Opened 2023-02-24 08:46 UTC by songpengyuan

### Ⅰ. Describe what this PR did
- Project Add LICENSE File
- Add code style check in front end (according to ice specification)
- Fix/ignore historical code style style

### Ⅱ. Does this pull request fix one issue?

#65 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
Manual test

### Ⅳ. Describe how to verify it
Manual

### Ⅴ. Special notes for reviews
- New code check npm command
    - `npm run lint`
    - `npm run eslint`
    - `npm run eslint:fix`
    - `npm run stylelint`

2023-02-25 08:04 UTC, CH3CHO reviewed
Could you add a lint step to the github action?

By the way, could you give an example of lint failed? I tried to mess up some code lines but it still returned a pass.

![image](https://user-images.githubusercontent.com/2909796/221346172-f1d4ca8f-341b-4a2d-b9f8-000eeaa72b4d.png)

2023-02-27 11:32 UTC, songpengyuan commented on frontend/.eslintignore
> +
New commit: Add .ts file format eslint check

test Demo:
```js
const testEslint = (a, b) => {
  console.log(a); // Unexpected console statement         
  const c = 100; 
  c = 100; // 'c' is constant    
  return; // Unnecessary return statement   
};

testEslint; // Expected an assignment or function call and instead saw an expression
```
![20230227192446](https://user-images.githubusercontent.com/30040339/221552835-3c0cc788-98a3-4452-9602-6fd29d3fbc0e.jpg)

2023-02-27 13:44 UTC, CH3CHO reviewed
Looks good now. Could you add a lint step to the github action?

2023-03-01 12:29 UTC, songpengyuan commented
feat: suppress errors in git hooks

![image](https://user-images.githubusercontent.com/30040339/222139595-213603b3-a408-47e4-96df-17bd9810e3bc.png)

2023-03-01 12:55 UTC, CH3CHO commented
> feat: suppress errors in git hooks
> 
> ![image](https://user-images.githubusercontent.com/30040339/222139595-213603b3-a408-47e4-96df-17bd9810e3bc.png)

Actually, I wasn't talking about Git hooks, but [GitHub action](https://github.com/features/actions).

You can talk a look at this: https://github.com/higress-group/higress-console/blob/main/.github/workflows/build-and-test.yaml

2023-03-01 14:08 UTC, CH3CHO requested changes
Actually, I wasn't talking about Git hooks, but [GitHub action](https://github.com/features/actions).

2023-03-08 00:51 UTC, songpengyuan commented
> 实际上，我不是在谈论 Git hooks，而是[GitHub action](https://github.com/features/actions)。

Done

![image](https://user-images.githubusercontent.com/30040339/223590554-2fba759a-8e8a-4ff0-88bf-6d8201ff9d69.png)

2023-03-08 03:45 UTC, CH3CHO requested changes

2023-03-08 03:45 UTC, CH3CHO commented on .github/workflows/frontend-code-checker.yaml
> +        node-version: [14.x, 16.x, 18.x]
我们现在打包用的是16，所以这里可以考虑只跑16节约时间。
另外这里跑不同的版本会产生不同的结果吗？

2023-03-08 03:45 UTC, CH3CHO commented on .github/workflows/frontend-code-checker.yaml
> +      - name: check
为什么这个命名就不 cd frontend 了。。。

2023-03-08 06:50 UTC, songpengyuan commented on .github/workflows/frontend-code-checker.yaml
> +      - name: check
我来修改下名字

cd frontend && npm run lint

2023-03-08 10:47 UTC, CH3CHO approved these changes
LGTM

2023-03-08 10:49 UTC, merged