helm dependencies add cert-manager
higress-group/higress-console pull request #125
Opened 2023-02-27 13:28 UTC by zyhui98

### Ⅰ. Describe what this PR did
#109 

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-03-02 07:58 UTC, CH3CHO requested changes
Could you make cert-manager an optional dependency?

2023-03-15 06:54 UTC, zyhui98 commented
> Could you make cert-manager an optional dependency?

ok, like other compenent, eg prometheus ?

2023-03-15 06:56 UTC, CH3CHO commented
> > Could you make cert-manager an optional dependency?
> 
> ok, like other compenent, eg prometheus ?

Right.

2023-03-23 13:10 UTC, zyhui98 commented
> > > Could you make cert-manager an optional dependency?
> > 
> > 
> > ok, like other compenent, eg prometheus ?
> 
> Right.

fix ok

2023-03-23 13:11 UTC, CH3CHO requested changes

2023-03-23 13:11 UTC, CH3CHO commented on helm/templates/cert-manager.yaml
> +{{- if .Values.o11y.enabled }}
cert-manager 不算 o11y 组件吧

2023-03-23 13:24 UTC, zyhui98 commented on helm/templates/cert-manager.yaml
> +{{- if .Values.o11y.enabled }}
yes, i changed

2023-03-23 13:32 UTC, zyhui98 commented on helm/templates/cert-manager.yaml
> +{{- if .Values.o11y.enabled }}
> cert-manager 不算 o11y 组件吧

好了

2023-03-23 13:47 UTC, CH3CHO approved these changes

2023-03-23 13:47 UTC, merged