fix: fix key_auth plugin spec
higress-group/higress-console pull request #161
Opened 2023-03-25 06:01 UTC by casun18

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

[#135](https://github.com/higress-group/higress-console/issues/135)

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-03-25 13:12 UTC, CH3CHO requested changes

2023-03-25 13:12 UTC, CH3CHO commented on backend/src/main/resources/plugins/key-auth/spec.yaml
> +          description: 配置 true 时，网关会尝试从 URL 参数中解析 API Key，注意in_query 和 in_header 至少有一个为 true。
`注意`前面建议改成句号，后面加一个空格。

2023-03-25 13:12 UTC, CH3CHO commented on backend/src/main/resources/plugins/key-auth/spec.yaml
> +          description: 配置 true 时，网关会尝试从 URL 参数中解析 API Key，注意in_query 和 in_header 至少有一个为 true。
同上

2023-03-25 13:12 UTC, CH3CHO commented on backend/src/main/resources/plugins/key-auth/spec.yaml
> +          en-US: When configured true, the gateway will try to parse the API Key from the URL parameters.Note that at least one of in_query and in_header is true.
英文句号后面是要加一个空格的。

2023-03-25 13:12 UTC, CH3CHO commented on backend/src/main/resources/plugins/key-auth/spec.yaml
> +          en-US: When configured true, the gateway will try to parse the API Key from the HTTP request header.Note that at least one of in_query and in_header is true.
同上

2023-03-26 06:46 UTC, casun18 commented on backend/src/main/resources/plugins/key-auth/spec.yaml
> +          en-US: When configured true, the gateway will try to parse the API Key from the HTTP request header.Note that at least one of in_query and in_header is true.
done

2023-03-26 07:32 UTC, CH3CHO approved these changes
LGTM

2023-03-26 07:33 UTC, merged