fix: add route plugin get/update api
higress-group/higress-console pull request #185
Opened 2023-04-06 11:40 UTC by songpengyuan

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

#182 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-04-06 12:09 UTC, CH3CHO requested changes

2023-04-06 12:09 UTC, CH3CHO commented on frontend/src/services/plugin.ts
> +export const updateRoutePluginInstances = (params: { routeName: string; pluginName: string }, payload) => {
routeName + pluginName 只能对应一个 instance。这几个方法都改成单数吧，包括上面 global 的

2023-04-07 02:22 UTC, songpengyuan commented on frontend/src/services/plugin.ts
> +export const updateRoutePluginInstances = (params: { routeName: string; pluginName: string }, payload) => {
Done

2023-04-07 06:00 UTC, johnlanni approved these changes
LGTM

2023-04-07 06:01 UTC, merged