feat: Add plugins to higress console
higress-group/higress-console pull request #315
Opened 2024-06-22 04:00 UTC by cr7258

<img width="1913" alt="image" src="https://github.com/higress-group/higress-console/assets/40051120/891aebe9-4a68-4089-aab8-34a365108faf">

<img width="1907" alt="image" src="https://github.com/higress-group/higress-console/assets/40051120/90ed05fa-e5d7-4771-98f9-f3910c0ca479">

# Related PR

Update the higress documentation to ensure that the plugin name is consistent with higress console.

2024-06-25 07:56 UTC, johnlanni requested changes

2024-06-25 07:56 UTC, johnlanni commented on backend/sdk/src/main/resources/plugins/basic-auth/spec.yaml
> +  priority: 10
已有的priority不要做调整，我们企业版也是统一的priority

2024-06-25 08:10 UTC, cr7258 commented on backend/sdk/src/main/resources/plugins/basic-auth/spec.yaml
> +  priority: 10
ok, 那已有的 priority 有没有什么规律可以遵循？

2024-06-27 03:11 UTC, cr7258 commented on backend/sdk/src/main/resources/plugins/basic-auth/spec.yaml
> +  priority: 10
@johnlanni 我把现有的 priority 恢复了，并且基于现有的规律调整了新增插件的 priority。

```yaml
# AUTHN

ai-cache
  phase: AUTHN
  priority: 10

## Request Restriction
ip-restriction
  phase: AUTHN
  priority: 210

request-validation
  phase: AUTHN
  priority: 220

## Authentication 
key-auth
  phase: AUTHN
  priority: 310
basic-auth
  phase: AUTHN
  priority: 320
hmac-auth
  phase: AUTHN
  priority: 330
jwt-auth
  phase: AUTHN
  priority: 340
oidc
  phase: AUTHN
  priority: 350

## Request/Response Transformation
transformer
  phase: AUTHN
  priority: 410
cache-control
  phase: AUTHN
  priority: 420
de-graphql
  phase: AUTHN
  priority: 430
custom-response
  phase: AUTHN
  priority: 910


# AUTHZ
## Security
bot-detect
  phase: AUTHZ
  priority: 310
request-block
  phase: AUTHZ
  priority: 320
waf
  phase: AUTHZ
  priority: 330
cors
  phase: AUTHZ
  priority: 340

# UNSPECIFIED_PHASE
## Traffic Management
key-rate-limit
  phase: UNSPECIFIED_PHASE
  priority: 10
cluster-key-rate-limit
  phase: UNSPECIFIED_PHASE
  priority: 20

## Application
ai-proxy
  phase: UNSPECIFIED_PHASE
  priority: 100
ai-statistics
  phase: UNSPECIFIED_PHASE
  priority: 200
ai-security-guard
  phase: UNSPECIFIED_PHASE
  priority: 300
ai-rag
  phase: UNSPECIFIED_PHASE
  priority: 400
ai-prompt-decorator
  phase: UNSPECIFIED_PHASE
  priority: 450
ai-prompt-template
  phase: UNSPECIFIED_PHASE
  priority: 500
ai-transformer
  phase: UNSPECIFIED_PHASE
  priority: 550
ai-token-ratelimit
  phase: UNSPECIFIED_PHASE
  priority: 600
```

2024-06-28 09:57 UTC, merged