draft of plugin forms
higress-group/higress-console pull request #322
Opened 2024-08-12 05:08 UTC by guluguluhhhh

draft of plugin forms

2024-08-12 05:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/higress-group/higress-console?pullRequest=322) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/higress-group/higress-console?pullRequest=322) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/higress-group/higress-console?pullRequest=322) it.</sub>

2024-08-12 05:32 UTC, CH3CHO commented on frontend/ice.config.mts
> +      target: "http://127.0.0.1:8080/",
以上两个本地开发改动不要提交上来

2024-08-12 08:17 UTC, CH3CHO commented
2024/08/12:
1. YAML 和表单要做在一个页面上。目标是用户可以自由切换编辑方式，且保留当前的编辑状态。现在看上去切换的时候每次都会重新加载页面，这样不行的；
2. 这几个地方好像没有显式 title，而显示的是 name：
    ![image](https://github.com/user-attachments/assets/b4348bd4-5c93-452a-b658-6a28fad29044)
3. allow 这种基本类型数组的显示效果不太好，你有什么建议吗？
    ![image](https://github.com/user-attachments/assets/c9495bfd-56a3-4f0e-af4b-87bf217c5f8c)

2024-09-23 09:13 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/ArrayForm/index.tsx
> +      console.error('Save failed:', errInfo);
冒号后面加个空格更好看

2024-09-23 09:16 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/ArrayForm/index.tsx
> +        translatedTitle = (prop['x-title-i18n'][i18next.language]) ? prop['x-title-i18n'][i18next.language] : key;
我建议是这里不要搞太复杂，就两次fallback，先看x-title-i18n里有没有对应语言，没有的话就直接拿title，title也没有的话就用key。另外，取prop['x-title-i18n']最好判断一下是不是真的有这么个字段，不然会直接undefined报错吧？

2024-09-23 09:17 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/ArrayForm/index.tsx
> +    title: t('route.factorGroup.columns.operation'),
这个资源可以考虑放到misc里面

2024-09-23 09:20 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/ArrayForm/index.tsx
> +    newData.splice(index, 1, {
这里直接 `newData[index] = newItem;` 可以吗？

2024-09-23 09:21 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/ArrayForm/index.tsx
> +        required: col.required,  // 添加 required 属性
无效注释

2024-09-23 09:21 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/ArrayForm/index.tsx
> +        {t('route.factorGroup.parameter')}
这个也可以考虑挪到misc了，尽量避免用别的页面的资源。

2024-09-23 09:23 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail_form.tsx
> +      const scm = formValuesToSchema(values);
原来是 schema 么。。。要不咱还是就用 schema 吧。。。

2024-09-23 09:24 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail_form.tsx
> +const GlobalPluginDetail_form = forwardRef((props: IProps, ref) => {
这里可以叫 GlobalPluginDetailForm 吗？

2024-09-23 09:24 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail_form.tsx
> +
多余的空行

2024-09-23 09:26 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail_form.tsx
> +        // 如果是嵌套的对象，则递归生成子表单
这种就是有效注释

2024-09-23 09:26 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail_form.tsx
> +          tip = value['x-description-i18n'] && value['x-description-i18n'][i18next.language];
类似这种读取多语言的逻辑感觉可以抽个函数出来

2024-09-23 09:27 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail_form.tsx
> +          if (Array.isArray(value)) {
这种嵌套逻辑不要做太多层，不便于阅读。建议取反之后先continue。

2024-09-23 09:32 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail_form.tsx
> +                // 如果删除 Item 后，对象只剩下 uid，则返回 false 表示要删除该项
说实话，这句注释写了还不如不写。不写的话别人看代码会理解删除uid和Item之后对象为空，那就不要它了。但加了之后别人会想：

1. 删除 Item 也不是一定会做的么。。。
2. uid 不是已经删除了，怎么还只剩下 uid？

写了备注如果别人还要思考的话，那可能这个备注写的就不太好。。。

2024-09-23 09:33 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail_form.tsx
> +                // 如果对象有 Item 属性，并且 Item 值为 null，则删除 Item
注释不是描述你做了什么，而是为什么要这么做。

“如果对象有 Item 属性，并且 Item 值为 null，则删除 Item”这句话给到GPT怀疑都能把下面的代码生成出来，所以和代码一一对应的注释是没啥意义的。

2024-10-02 06:08 UTC, guluguluhhhh commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail_form.tsx
> +      const scm = formValuesToSchema(values);
当时考虑的是，因为直接拿到的schema、表单值的form_values以及要给后端的yaml，格式都不一样，所以写了几个函数来转换(•ө•)

2024-10-05 07:36 UTC, CH3CHO commented
建议兼容一下规范里的 scope 字段：https://higress.io/docs/latest/user/wasm-image-spec/ 。这个字段现在的名字不太对，后面会改成 x-scope。

https://github.com/higress-group/higress-group.github.io/pull/325/files

2024-10-05 07:39 UTC, CH3CHO commented
Basic Auth 插件，YAML 里是有 consumer 信息的，但切到表单就什么都没有了，这个不太对把？

2024-10-05 07:39 UTC, CH3CHO requested changes

2024-10-05 07:39 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/index.tsx
> +            onClick={() => setIsFormView(!isFormView)}
两个问题：
1. 这里只需要切下面的编辑区，开启状态不需要参与切换吧？
2. 切换的时候会触发重新加载配置，这个是没有必要的。而且也应该允许用户先用表单编辑，然后切到 YAML 下面并保留表单编辑的内容。

2024-10-05 07:39 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetailForm.tsx
> +      return (<div>inValid schema!</div>)
首先，invalid 是一个单词。另外，这种情况下，应该告诉用户由于 schema 信息无法正常解析，本插件只支持 YAML 编辑方式。

2024-10-05 07:39 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/index.tsx
> +            onClick={() => setIsFormView(!isFormView)}
你可以试试把这两种编辑方式做成 tab 的形式。

2024-10-05 07:39 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetailForm.tsx
> +          fieldComponent = (
boolean 这里用类似开启状态的那种开关是不是更好？

2024-10-05 07:39 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/index.tsx
> +            onClick={() => setIsFormView(!isFormView)}
这里可以判断一下加载的 schema 是不是空的。如果是空的，就不需要显示表单编辑器。另外建议默认是表单编辑器，这样对用户更友好一些。

2024-10-05 08:15 UTC, guluguluhhhh commented
> Basic Auth 插件，YAML 里是有 consumer 信息的，但切到表单就什么都没有了，这个不太对把？

老师您好，现在的功能是只有点击右上角保存之后，另一边的内容才会同步，是需要改成一直都同步吗？

2024-10-05 08:16 UTC, CH3CHO commented
> > Basic Auth 插件，YAML 里是有 consumer 信息的，但切到表单就什么都没有了，这个不太对把？
> 
> 老师您好，现在的功能是只有点击右上角保存之后，另一边的内容才会同步，是需要改成一直都同步吗？

建议是随时同步。YAML 和表单应该是两种编辑模式，在编辑过程中用户可以自由切换，在 schema 范围内不影响配置内容的，不要求必须先保存。你看看好不好做。

2024-10-05 08:18 UTC, guluguluhhhh commented
> > > Basic Auth 插件，YAML 里是有 consumer 信息的，但切到表单就什么都没有了，这个不太对把？
> > 
> > 
> > 老师您好，现在的功能是只有点击右上角保存之后，另一边的内容才会同步，是需要改成一直都同步吗？
> 
> 建议是随时同步。YAML 和表单应该是两种编辑模式，在编辑过程中用户可以自由切换，在 schema 范围内不影响配置内容的，不要求必须先保存。你看看好不好做。

好的我试试~

2024-10-05 16:12 UTC, guluguluhhhh commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetailForm.tsx
> +                }
老师您好，这里“Item”是作为纯数组类型字段的里item的名字
![81f4a64051052b9e2354baacbaa3679](https://github.com/user-attachments/assets/585b82cc-10d2-45f6-bf1b-52228c3338bf)
当时发现如果不删的话会在yaml那边会直接显示为Item: null，object数组没这个情况，所以就想着Item为空的时候就把他删了

2024-10-06 03:18 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetailForm.tsx
> +                }
哦哦，注释里说明一下就好了。

2024-10-07 13:46 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/index.tsx
> +        <Tabs activeKey={currentTabKey} onChange={(key) => setCurrentTabKey(key)}>
Tab 的文本一般不会说自己是切换到什么什么吧？

2024-10-08 03:31 UTC, guluguluhhhh commented on frontend/src/pages/plugin/components/PluginDrawer/index.tsx
> +        <Tabs activeKey={currentTabKey} onChange={(key) => setCurrentTabKey(key)}>
噢噢，意思是要直接说“表单视图”，“YAML视图”，这样吗？

2024-10-08 03:36 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/index.tsx
> +        <Tabs activeKey={currentTabKey} onChange={(key) => setCurrentTabKey(key)}>
可以先这样写

2024-10-08 03:42 UTC, guluguluhhhh commented on frontend/src/pages/plugin/components/PluginDrawer/index.tsx
> +        <Tabs activeKey={currentTabKey} onChange={(key) => setCurrentTabKey(key)}>
嗯嗯好的

2024-10-14 05:39 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetailForm.tsx
> +          fieldComponent = (
为了和最顶部的插件开关区分，这里先保持现状。

2024-10-14 06:52 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail_form.tsx
> +          if (Array.isArray(value)) {
这个计划修改吗？

2024-10-14 06:54 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetailForm.tsx
> +                }
这里标注一下 uid、Item 两个字段分别做什么用的，为什么需要删除就好了。

2024-10-14 06:55 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetailForm.tsx
> +        result += `${indent}${key}:\n${schemaToYaml(value, indent + '  ')}`;
这个还计划修改吗？

2024-10-14 07:01 UTC, guluguluhhhh commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetailForm.tsx
> +        result += `${indent}${key}:\n${schemaToYaml(value, indent + '  ')}`;
修改过了，老师，如上面几行的注释，我加了个firstentry来判断第一行直接跟在 - 后面。调试的时候发现直接改这一行的话整体缩进会有问题。

2024-10-14 07:26 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetailForm.tsx
> +import { Alert, Form, Spin, Switch, message, Space, Typography, Input, Select } from 'antd';
借用这个地方记录几个 bug：

1. 表单视图不会显示系统自带的示例配置信息
2. 打开编辑对话框后，首次切换到 YAML 视图还有一次加载配置的过程
3. 每次打开编辑对话框时应清除上下文。实测发现，打开A插件对话框然后关闭，再打开B插件对话框，加载B配置的请求超时，页面会显示A插件的配置和表单

2024-10-18 09:03 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail.tsx
> +        <Form name="basic" form={form} autoComplete="off" layout="vertical" onFieldsChange={fieldChange} key={defaultValue}>
key={defaultValue} 是啥意思？

2024-10-18 12:20 UTC, guluguluhhhh commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail.tsx
> +        <Form name="basic" form={form} autoComplete="off" layout="vertical" onFieldsChange={fieldChange} key={defaultValue}>
老师您好，我这里是希望form的内容能够根据defaultValue的改变来动态渲染。不加这个的话，tab切换的时候，表单值换不过来。

2024-10-20 03:42 UTC, CH3CHO reviewed
So far so good.

2024-10-20 09:05 UTC, CH3CHO requested changes
- [x] 如果用户选择使用 YAML 编辑器，则无需校验表单内容。可以用 basic-auth 进行测试。默认状态下，由于没有配置 allow，表单那边是过不了校验的。但如果用户选择了自己编写 YAML，这里可以无需校验，而且如果表单编辑器有 bug，用户仍然可以继续使用 YAML 编辑器修改配置
- [x] 鉴于 tab 里已经说明了这是 YAML 视图，下图红框中的标题可以去掉
    ![image](https://github.com/user-attachments/assets/94f3039c-403b-4c63-b3ca-10b0b2039458)
- [ ] 列表类型的必填验证有点奇怪，有的时候空数组能过 required，有的时候过不了。如果列表类型是必填的话，原则上空数组是不应该过的，建议看一下这块的校验规则
- [x] 【可选】代码里的注释建议改为英文
- [x] 字符串数组转出来的 YAML 不太对
   ![image](https://github.com/user-attachments/assets/adcdcea6-29aa-46bd-8ce4-772c0e9c4cfb)
   ![image](https://github.com/user-attachments/assets/0227fae6-3bc2-4bcf-9c51-99add5d42462)
- [x] 如果一个数组里没东西了，可以考虑直接不写这个数组，或者写 []，再或者写 null
   ![image](https://github.com/user-attachments/assets/dd9d829a-d508-4efc-b5cd-0c7479f0a512)
   而且我还遇到了同样是空数组，两个字段转出来的 YAML 不一样的情况。。。
   ![image](https://github.com/user-attachments/assets/c5afd2bb-c02a-4880-bb3b-7ed6baa4ed43)
- [x] 表单的请输入提示没有翻译
   ![image](https://github.com/user-attachments/assets/ddaa4d7e-f2a6-444a-9f8c-ddac9b839e2b)
- [ ] 如果遇到不支持的类型或者其他解析失败，不要报错，统一走 schema 无法解析的分支，避免由于 schema 结构问题阻塞用户配置（建议catch一下）
   ![image](https://github.com/user-attachments/assets/8a39c64d-4075-4539-ad76-e248b0f978fd)
   https://swagger.io/specification/
   ![image](https://github.com/user-attachments/assets/3b73b064-a720-4500-9dfe-f1a2255da2ba)
- [ ] 如果是一个简单对象里包含了若干个字段，在生成表单的时候需要给这个对象加个单独的 item 用来标识，不然它的内部字段和平级字段就分不出来了   
   ![image](https://github.com/user-attachments/assets/9fca93e9-fcaa-4db9-9c15-7ff1d67fb33d)
   ![image](https://github.com/user-attachments/assets/e7ca41e0-4386-4064-888c-8b019198c32a)
- [ ] 数值型和布尔型的数组生成的表单不对
   ![image](https://github.com/user-attachments/assets/86dc6943-6b11-4bbb-8129-98a320a6367a)
   ![image](https://github.com/user-attachments/assets/fc0aabe9-3ae3-4210-baeb-18e12a9b2be1)

2024-10-20 09:05 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail.tsx
> +          dict[value.items.title] = value.items;
items 是不是都没有 title？

2024-10-23 09:05 UTC, CH3CHO reviewed
So far so good.

2024-10-23 11:06 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/ArrayForm/index.tsx
> +        <Select ref={inputRef} onPressEnter={save} onBlur={save}>
Select 是没有 onPressEnter 的，要删掉。浏览器的 Console 里会有报错。

2024-10-23 11:06 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail.tsx
> +          key={translatedTitle}
这个 key 循环里的唯一标识，但 translatedTitle 我担心会有冲突的。建议还是用 fullKey 更安全。

2024-10-23 11:06 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail.tsx
> +              name={fullKey}
这个 Form.Item 没有 key。

2024-10-23 11:06 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail.tsx
> +              name={fullKey}
这里的问题是 ArrayForm 的 validation 不会透到外面阻塞保存，不是很合理。这个应该也是和 handleSave 那个问题有直接关系的。

2024-10-23 13:47 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail.tsx
> +          // The UID is used to uniquely identify each data item. But the transformation result does not need to display the UID, so it is removed here.
这段逻辑和下面的 removeOnlyUidItems 是不是有点重复？

2024-10-25 01:08 UTC, CH3CHO commented on frontend/src/pages/plugin/components/PluginDrawer/GlobalPluginDetail.tsx
> +      return Object.values(value.properties).every(property => {
你这样写，object 里是不是就不能有 array 和 object 类型的字段了？

2024-10-25 02:03 UTC, CH3CHO approved these changes
Well done!

2024-10-25 03:29 UTC, CH3CHO reviewed
Mark

2024-10-25 06:12 UTC, merged