feature: Implement domain management to configmap/secret model mappin…
higress-group/higress-console pull request #40
Opened 2023-02-01 13:54 UTC by Hinsteny

Ⅰ. Describe what this PR did
Finished the issues https://github.com/higress-group/higress-console/issues/18
Ⅱ. Does this pull request fix one issue?
No
Ⅲ. Why don't you add test cases (unit test/integration test)?
I will add unit test case in another PR later.
Ⅳ. Describe how to verify it
I had do test in local with postman.
Ⅴ. Special notes for reviews
NO

2023-02-01 13:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/higress-group/higress-console?pullRequest=40) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/higress-group/higress-console?pullRequest=40) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/higress-group/higress-console?pullRequest=40) it.</sub>

2023-02-02 02:16 UTC, johnlanni commented
@Hinsteny Please resolve the confilcting files.

2023-02-02 02:16 UTC, johnlanni commented
cc @CH3CHO

2023-02-02 02:51 UTC, CH3CHO requested changes
Please check out inline comments.

2023-02-02 02:51 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/DomainServiceImpl.java
> +                .startsWith(CommonKey.HIGRESS_DOMAIN + CommonKey.HIGRESS_HORIZONTAL_LINE))
虽然用名字区分比较直观，但从查询角度，这里是否用Label做过滤更好一些？

2023-02-02 02:51 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/DomainServiceImpl.java
> +                                    CommonKey.HIGRESS_WILDCARD);
类似的replace逻辑多处出现。建议抽一个方法出来。

2023-02-02 02:51 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/DomainServiceImpl.java
> +        Assert.isTrue(StringUtils.equals(v1Status.getStatus(), "Success"),
这里如果Assert失败会抛IllegalArgumentException，与场景不符。建议对此进行封装，抛出合适的业务自定义异常，或者直接用ApiExcepion？

2023-02-02 02:51 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +    public static V1ConfigMap convertDomainToV1ConfigMap(Domain domain) {
上面的模型转换方法都是实例级的，这里用 static 是否不太合适？另外对 domainName 与 ConfigMap name 的格式转换逻辑分散在 KubernetesClientService 和 KubernetesModelConverter 两处。建议收口一下。

2023-02-02 02:51 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +                .substring((CommonKey.HIGRESS_DOMAIN + CommonKey.HIGRESS_HORIZONTAL_LINE).length());
名字是不是直接写到 ConfigMap 里更好？而且万一域名本身就是 wildcard.xxx.com，会不会有问题？而且万一 wildcard 夹在域名中间呢，比如 www.wildcard.com、www.wildcardtest.com？

2023-02-02 02:51 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/controller/DomainController.java
> +                return ResponseEntity.noContent().build();
这个 noContent 是否会对前端的处理产生影响？

2023-02-02 02:51 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/controller/DomainController.java
> +        return ResponseEntity.status(code)
这里是不还是返回 Result 比较好？

2023-02-03 10:05 UTC, CH3CHO requested changes
Please check out inline comments below.

2023-02-03 10:05 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +    private static Map<String, String> buildResourceLabels() {
这个 label 是不是有必要给所有通过 Console 创建的 CR 数据都打上呢？如果是的话，那完全可以在 ClientService 里强制加上。

2023-02-03 10:05 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/DomainServiceImpl.java
> +                CommonKey.NS_DEFAULT, domainConfigMap.getMetadata().getName(), domainConfigMap);
我觉得 NS 这部分逻辑可以统一收口在 ClientService 里，是读所有 NS 的，还是只读特定 NS 的。你怎么看呢？

2023-02-03 10:05 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/DomainServiceImpl.java
> +                + domainName.replace(CommonKey.ASTERISK, CommonKey.WILDCARD);
这个是不是应该替换成那个方法？

2023-02-03 10:09 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +        domainConfigMap.getMetadata().setNamespace(CommonKey.NS_DEFAULT);
比如Ingress，Route模型里是有namespace的，所以这个其实前端可以指定。Domain这个比较核心的模型，其实存哪都无所谓，可以考虑在 ClientService 里收口。

2023-02-03 11:31 UTC, Hinsteny commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +    private static Map<String, String> buildResourceLabels() {
按照目前的label定义，我支持给所有CR数据都打上；
higress.io/resource-definer=higress

2023-02-03 12:52 UTC, Hinsteny commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +        domain.setName(configMap.getData().get(CommonKey.DOMAIN));
1、我额外加个判空抛出异常处理，避免NPE；正常由Higress插入的ConfigMap都应该有data属性；
2、OK

2023-02-04 03:52 UTC, CH3CHO reviewed
只有一些小建议了，基本没什么问题。

2023-02-04 03:52 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java
> +    public final static String K8S_CONFIGMAP = "ConfigMap";
9、10 两行这两个常量应该是没用了。建议删除。

2023-02-04 03:52 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +            throw new RuntimeException("Get ConfigMap from k8s is illegal");
是不是IllegalArgumentException更合理？另外"Get ConfigMap from k8s is illegal"这句错误信息翻译过来是什么呢？

2023-02-04 03:52 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java
> +        labels.put(Label.RESOURCE_DEFINER_KEY, Label.RESOURCE_DEFINER_VALUE);
这里不建议直接修改输入参数，而是复制一份，避免对调用方产生意外的影响。

2023-02-04 03:52 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java
> +    private String renderDefaultLabels(String labels) {
这个在名字里标明是labelSelector更好一些？

2023-02-04 04:23 UTC, CH3CHO approved these changes

2023-02-04 06:06 UTC, merged