create,update,list,delete mcpbridge
higress-group/higress-console pull request #73
Opened 2023-02-09 10:45 UTC by wojesen

### Ⅰ. Describe what this PR did

create,update,list,delete mcpbridge
### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2023-02-09 10:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/higress-group/higress-console?pullRequest=73) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/higress-group/higress-console?pullRequest=73) before we can accept your contribution.<br/><hr/>**wang.jinshan3** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/higress-group/higress-console?pullRequest=73) it.</sub>

2023-02-10 03:42 UTC, CH3CHO requested changes
请查看代码内评论。另外对所有文件都进行一下格式化。

2023-02-10 03:42 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceService.java
> +    ServiceSource query(String name) throws BusinessException;
BusinessException 是 RuntimeException，可以不用写 throws。

2023-02-10 03:42 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/controller/dto/ServiceSource.java
> +        if(KubernetesConstants.REGISTRY_TYPE_ZK.equals(this.getType())
if后面应该有空格的，建议格式化一下。

2023-02-10 03:42 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/controller/dto/ServiceSource.java
> +                && (null == this.getProperties().get("nacosNamespaceId") || StringUtils.isBlank((String)this.getProperties().get("nacosNamespaceId")))){
类似的属性名称建议做成常量。

2023-02-10 03:42 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/controller/dto/ServiceSource.java
> +                && (null == this.getProperties().get("nacosNamespaceId") || StringUtils.isBlank((String)this.getProperties().get("nacosNamespaceId")))){
而且为什么有的地方用的是字段有的地方用的是getter呢？

2023-02-10 03:42 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/controller/dto/ServiceSource.java
> +        if(null == this.port || null == this.properties){
如果要校验的话，port是否有必要校验范围呢？

2023-02-10 03:42 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/controller/dto/RegistryConfig.java
> +    private  String name;
整个文件建议格式化一下。private 后面有的空两格有的空一格，字段之间有的空一行有的空两行，这是为什么呢？

2023-02-10 03:42 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/controller/ServiceSourceController.java
> +            throw new ValidationException("serviceSource name in the URL doesn't match the one in the body.");
这个错误信息好像和错误场景不匹配。

2023-02-10 03:42 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/controller/ServiceSourceController.java
> +            throw new ValidationException("serviceSource name in the URL doesn't match the one in the body.");
这个错误信息好像和错误场景不匹配。

2023-02-10 03:42 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java
> +    public static final String REGISTRY_TYPE_NACOS_NACOSNAMESPACEID = "nacosNamespaceId";
常量名称最后一段是否也需要按单词分开呢？

2023-02-10 03:42 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java
> +        List<ServiceSource> serviceSources = new ArrayList<>();
这里可以考虑用`Collections.emptyList()`，减少一个对象创建。

2023-02-10 03:42 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java
> +        if(null != v1McpBridge && !CollectionUtils.isEmpty(v1McpBridge.getSpec().getRegistries())){
Spec是否需要判空？

2023-02-10 03:42 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java
> +        Optional<V1RegistryConfig> op = v1McpBridge.getSpec().getRegistries().stream().filter(r -> StringUtils.isNotBlank(r.getName()) && name.equals(r.getName())).findFirst();
如果name不为空，为什么需要先判断r的name是不是空？如果name是空，那么name.equals是否安全？

2023-02-10 03:42 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java
> +            return op.map(kubernetesModelConverter::v1RegistryConfig2ServiceSource).get();
这里有必要判断么，直接getOrElse是否可以？

2023-02-10 03:42 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java
> +    public static final String MCP_BRIDGE_VERSION = "networking.higress.io/v1";
感觉上面几个常量是不是放到V1McpBridge对象里用起来更方便？

2023-02-10 06:09 UTC, johnlanni commented
@wojesen Please sign the CLA

> [![CLA assistant check](https://camo.githubusercontent.com/4c970efeed75dd01f6778bf7e33dec85e4171375cb69acb0927bfc9d437d78d9/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/higress-group/higress-console?pullRequest=73) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/higress-group/higress-console?pullRequest=73) before we can accept your contribution.
> 
> **wang.jinshan3** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/higress-group/higress-console?pullRequest=73) it.

2023-02-10 06:12 UTC, johnlanni commented
![image](https://user-images.githubusercontent.com/6763318/218016098-5fafcec1-7860-4928-b32d-13c30d7bb57d.png)
@wojesen commit的username和email请确保和github账号一致

2023-02-10 07:52 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceService.java
> +    ServiceSource query(String name) throws BusinessException;
已去掉

2023-02-10 07:53 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/controller/dto/ServiceSource.java
> +        if(KubernetesConstants.REGISTRY_TYPE_ZK.equals(this.getType())
已格式化

2023-02-10 07:53 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/controller/dto/ServiceSource.java
> +                && (null == this.getProperties().get("nacosNamespaceId") || StringUtils.isBlank((String)this.getProperties().get("nacosNamespaceId")))){
已经修改

2023-02-10 07:53 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/controller/dto/ServiceSource.java
> +        if(null == this.port || null == this.properties){
已经添加

2023-02-10 07:53 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java
> +        List<ServiceSource> serviceSources = new ArrayList<>();
已修改

2023-02-10 07:53 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java
> +        if(null != v1McpBridge && !CollectionUtils.isEmpty(v1McpBridge.getSpec().getRegistries())){
已增加

2023-02-10 07:54 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java
> +        Optional<V1RegistryConfig> op = v1McpBridge.getSpec().getRegistries().stream().filter(r -> StringUtils.isNotBlank(r.getName()) && name.equals(r.getName())).findFirst();
这里name肯定非空，已经修改

2023-02-10 07:54 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java
> +            return op.map(kubernetesModelConverter::v1RegistryConfig2ServiceSource).get();
已修改

2023-02-10 07:54 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/constant/KubernetesConstants.java
> +    public static final String MCP_BRIDGE_VERSION = "networking.higress.io/v1";
已修改

2023-02-10 08:06 UTC, CH3CHO requested changes
请查看代码内评论。

2023-02-10 08:06 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java
> +            throw new BusinessException("Error occurs when add the serviceSource generated by serviceSource with name: "
这个报错信息有点奇怪啊

2023-02-10 08:06 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java
> +        io.kubernetes.client.openapi.JSON json = new io.kubernetes.client.openapi.JSON();
这里是不是可以用`client.getJSON()`？

2023-02-10 08:06 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java
> +                V1McpBridge.DEFAULT_VERSION, controllerNamespace, V1McpBridge.MCP_BRIDGE_PLURAL, "false", null, null,
pretty统一传false吧，和其他方法保持一致。

2023-02-10 08:06 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +    private static V1RegistryConfig serviceSource2V1RegistryConfig(ServiceSource serviceSource) {
这两个serviceSource2V1RegistryConfig方法重复的有点多啊

2023-02-10 08:09 UTC, CH3CHO requested changes

2023-02-10 08:09 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +            v1RegistryConfig.setZkServicesPath((List)Optional
这几行里的类型转换会触发一个unchecked warning。建议修改。

2023-02-10 08:17 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java
> +                V1McpBridge.DEFAULT_VERSION, controllerNamespace, V1McpBridge.MCP_BRIDGE_PLURAL, "false", null, null,
pretty改成boolean? 方法入参是string类型吧

2023-02-10 08:25 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +            v1RegistryConfig.setZkServicesPath((List)Optional
这里是否可以只做object的非空判断

2023-02-10 08:27 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +            v1RegistryConfig.setZkServicesPath((List)Optional
这里不需要判空吧，为空也没关系吧？

2023-02-10 08:32 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +            v1RegistryConfig.setZkServicesPath((List)Optional
serviceSource中字段类型为list,这里肯定会涉及到类型转换，有其他建议吗

2023-02-10 08:43 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +            v1RegistryConfig.setZkServicesPath((List)Optional
试试 (List<String>)

2023-02-10 08:46 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +            v1RegistryConfig.setZkServicesPath((List)Optional
这里已经用的(List)，你是说加的位置不对吗

2023-02-10 09:30 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +    private static V1RegistryConfig serviceSource2V1RegistryConfig(ServiceSource serviceSource) {
已修改

2023-02-10 09:31 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java
> +        io.kubernetes.client.openapi.JSON json = new io.kubernetes.client.openapi.JSON();
已修改

2023-02-10 09:31 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/ServiceSourceServiceImpl.java
> +            throw new BusinessException("Error occurs when add the serviceSource generated by serviceSource with name: "
已修改

2023-02-10 09:31 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +    private static void serviceSource2V1RegistryConfig(V1RegistryConfig v1RegistryConfig, ServiceSource serviceSource) {
已修改

2023-02-10 09:31 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +    public static void addV1McpBridgeRegistry(V1McpBridge v1McpBridge, ServiceSource serviceSource) {
已修改

2023-02-10 09:31 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/controller/util/ValidateUtil.java
> +    // 端口号验证 1 ~ 65535
已修改

2023-02-10 09:31 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/controller/util/ValidateUtil.java
> +        return Pattern.matches(regex, String.valueOf(port));
已修改

2023-02-10 09:42 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java
> +                V1McpBridge.DEFAULT_VERSION, controllerNamespace, V1McpBridge.MCP_BRIDGE_PLURAL, "false", null, null,
已经把pretty改成常量

2023-02-10 10:08 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +            v1RegistryConfig.setZkServicesPath((List)Optional
刚才没转义，泛型部分没出来。

2023-02-10 10:12 UTC, CH3CHO requested changes

2023-02-10 10:12 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +    public void fillServiceSourceInfo(ServiceSource serviceSource, V1RegistryConfig v1RegistryConfig) {
这个方法需要public吗？

2023-02-10 10:12 UTC, CH3CHO commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java
> +            return client.getJSON().deserialize(client.getJSON().serialize(response), V1McpBridge.class);
这里可以参考一下其他强类型的客户端，避免多次反序列化。

2023-02-10 10:34 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesClientService.java
> +            return client.getJSON().deserialize(client.getJSON().serialize(response), V1McpBridge.class);
意思是重写一下customObjectsApi吗

2023-02-10 10:38 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +    public void fillServiceSourceInfo(ServiceSource serviceSource, V1RegistryConfig v1RegistryConfig) {
已修改

2023-02-10 10:38 UTC, wojesen commented on backend/src/main/java/com/alibaba/higress/console/service/kubernetes/KubernetesModelConverter.java
> +            v1RegistryConfig.setZkServicesPath((List)Optional
已修改

2023-02-10 11:24 UTC, CH3CHO approved these changes
LGTM now.

2023-02-10 11:34 UTC, CH3CHO commented
> 

请重新理一下commit树，清理错误的author信息，不然没法合并。如果先合并其他PR，那么本PR的改动可能会出现冲突，导致无法直接合并。

@wojesen

2023-02-10 13:14 UTC, closed without merging