feat: add certificate manage page
higress-group/higress-console pull request #91
Opened 2023-02-16 14:39 UTC by Risker-C

### Ⅰ. Describe what this PR did
feat: add certificate manage page

### Ⅱ. Does this pull request fix one issue?

fixed #54 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews
接口联调未全部通过

2023-02-17 01:46 UTC, johnlanni commented
@Risker-C Please resolve the conflicts.

2023-02-17 01:46 UTC, johnlanni commented
cc @CH3CHO

2023-02-17 01:58 UTC, CH3CHO requested changes

2023-02-17 01:58 UTC, CH3CHO commented on frontend/src/locales/en-US/translation.json
> +    "CertManagement": "Certificate Management"
这个命名格式建议统一一下

2023-02-17 01:58 UTC, CH3CHO commented on frontend/src/locales/en-US/translation.json
> +      "version": "Certificate Version",
这个版本号可以不显示出来的，只是用于内部的版本控制，而且这个版本号对用户没有意义，

2023-02-17 01:58 UTC, CH3CHO commented on frontend/src/locales/en-US/translation.json
> +      "validityEnd": "Certificate validity expiration time",
上面3个对于表头来说是不是有点长？

2023-02-17 01:58 UTC, CH3CHO commented on frontend/src/locales/en-US/translation.json
> +      "nameTooltip": "Globally unique. The backend is directly associated with the Secret name under the Higress namespace in K8s.",
不用把实现方式告诉用户吧。

2023-02-17 01:58 UTC, CH3CHO commented on frontend/src/locales/en-US/translation.json
> +      "versionPlaceholder": "Please enter certificate version",
版本号不需要用户输入。

2023-02-17 01:58 UTC, CH3CHO commented on frontend/src/locales/en-US/translation.json
> +      "certTooltip": "Only for creating and updating",
还有别的场景吗。。。。

2023-02-17 01:58 UTC, CH3CHO commented on frontend/src/locales/en-US/translation.json
> +      "validityEndRequired": "Please select the certificate validity expiration time"
除了cert和key之外都是不需要输入的。后端可以从证书数据里解析出来。

2023-02-17 01:58 UTC, CH3CHO commented on frontend/src/locales/en-US/translation.json
> +      "keyPlaceholder": "Please enter certificate key",
类似的消息是否需要以句号结尾？

2023-02-17 01:58 UTC, CH3CHO commented on frontend/src/pages/tls-certificate/components/TlsCertificateForm/index.tsx
> +    const domains = _domains as TlsCertificate[];
domains？

2023-02-17 01:58 UTC, CH3CHO commented on frontend/src/pages/tls-certificate/components/TlsCertificateForm/index.tsx
> +      const { name,version, cert, key } = value;
这个逗号前后空格的格式建议统一

2023-02-17 01:58 UTC, CH3CHO commented on frontend/src/pages/tls-certificate/components/TlsCertificateForm/index.tsx
> +
多余的空行

2023-02-17 01:58 UTC, CH3CHO commented on frontend/src/pages/tls-certificate/index.tsx
> +      render: (value) => (value?.map(i => <p>{i}</p>) || '-'),
如果一个证书里有100多个域名，这里的显示会有问题吗？

2023-02-17 01:58 UTC, CH3CHO commented on frontend/src/pages/tls-certificate/index.tsx
> +
多余空行

2023-02-18 02:37 UTC, Risker-C commented on frontend/src/locales/en-US/translation.json
> +      "version": "Certificate Version",
ok

2023-02-18 02:40 UTC, Risker-C commented on frontend/src/pages/tls-certificate/components/TlsCertificateForm/index.tsx
> +      const { name,version, cert, key } = value;
ok

2023-02-19 01:34 UTC, CH3CHO requested changes
Please check out all the inline comments.

2023-02-19 01:34 UTC, CH3CHO commented on frontend/src/locales/en-US/translation.json
> +      "validityEnd": "Valid until",
这几个表头翻译，单词的首字母样式需要统一

2023-02-19 01:34 UTC, CH3CHO commented on frontend/src/pages/tls-certificate/index.tsx
> +        i.key || (i.key = i.id || i.name);
key 本来就是 certificate 的一个属性，会影响编辑界面的显示。需要思考一下怎么处理。

2023-02-19 01:34 UTC, CH3CHO commented on frontend/src/pages/tls-certificate/index.tsx
> +        i.key || (i.key = i.id || i.name);
而且模型里就没 id，这里不需要判断一次吧。

2023-02-19 01:34 UTC, CH3CHO commented on frontend/src/menuConfig.tsx
> +    icon: <KeyOutlined />,
可以比较一下 KeyOutlined 和 SafetyCertificateOutlined 这两个哪个显示效果更好一些。

2023-02-19 02:48 UTC, Risker-C commented on frontend/src/menuConfig.tsx
> +    icon: <KeyOutlined />,
已切换至新图标

2023-02-19 02:48 UTC, Risker-C commented on frontend/src/pages/tls-certificate/index.tsx
> +        i.key || (i.key = i.id || i.name);
已修改表格绑定的key值为具有唯一性的name属性

2023-02-19 02:48 UTC, Risker-C commented on frontend/src/locales/en-US/translation.json
> +      "validityEnd": "Valid until",
已修改

2023-02-19 03:07 UTC, CH3CHO requested changes
One thing remains.

2023-02-19 03:28 UTC, Risker-C commented on frontend/src/locales/en-US/translation.json
> +    "CertManagement": "Certificate Management"
不好意思，这里我确实忘记了，但是我不清楚应该如何修改，修改为Domain Manage吗？

2023-02-19 03:36 UTC, Risker-C commented on frontend/src/locales/en-US/translation.json
> +    "CertManagement": "Certificate Management"
> 这个还准备改吗？

不好意思，这里我确实忘记了，但是我不清楚应该如何修改，修改为Domain Manage吗？

2023-02-19 04:54 UTC, CH3CHO requested changes
One thing done. One thing new.

2023-02-19 04:54 UTC, CH3CHO commented on frontend/src/menuConfig.tsx
> +    name: 'menu.CertManagement',
这个大小写是不是不对诶？

2023-02-19 05:24 UTC, CH3CHO approved these changes
LGTM. Thanks.

2023-02-19 05:24 UTC, merged